### ISSUE TITLE
table page wish list

### ISSUE THREAD

**Issue by stlbucket** [stlbucket/postgraphile-db-inspector-extension#8]

**Comment by benjie** [comment]
Order for triggers should be:

- Timing (BEFORE, then AFTER)
- Name (lexicographically sorted)
- Trigger On (INSERT then UPDATE then DELETE)

As shown:

![Screenshot_20190820_180004](https://user-images.githubusercontent.com/129910/63367708-5b7c3480-c374-11e9-830d-924b61f81b91.png)

**Comment by benjie** [comment]
If "roles" only contains "public" in POLICIES then omit it, since this is the default and it adds visual noise:

![Screenshot_20190820_180048](https://user-images.githubusercontent.com/129910/63367782-7ea6e400-c374-11e9-83d1-78673c9db2cd.png)

**Comment by benjie** [comment]
Would prefer the permissions table use a column-per-permission approach, e.g.

![](https://www.sqlmaestro.com/data/help/postgresql/maestro/01_02_02_permissions.png)

**Comment by benjie** [comment]
Colourise or otherwise distinguish indices that belong to a constraint (a link to the constraint would be handy too):

![Screenshot_20190820_180414](https://user-images.githubusercontent.com/129910/63368052-fffe7680-c374-11e9-9d73-072461e9a97d.png)

(In this case there's the primary key constraint, but uniqueness constraints should also have this treatment.)
